name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch utama repo-mu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH=$HOME/.fly/bin:$PATH
          flyctl version

      - name: Deploy to Fly.io
        run: |
          flyctl auth docker
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
